arr = ["Penguin",
       "United States",
       "United Kingdoms",
       "Canada",
       "Australia",
       "China",
       "Japan",
       "Germany",
       "Russia",
       "France",
       "Singapore",
       "Israel",
       "Brazil",
       "Philippines",
       "Netherlands",
       "Pakistan",
       "Turkey",
       "South",
       "Mexico",
       "Indonesia",
       "Switzerland",
       "Iran",
       "Sweden",
       "Egypt",
       "Ireland",
       "Saudi Arabia",
       "Rabbit",
       "Shrimp",
       "Goat",
       "Deer",
       "Sheep",
       "Fish",
       "Turkey",
       "Crow",
       "Peacock",
       "Goose",
       "Stork",
       "Turkey",
       "Hawk",
       "Seagull",
       "Penguin",
       "Swan",
       "Chicken",
       "horse",
       "Chimpanzee",
       "Lion",
       "Panda",
       "Walrus",
       "Otter",
       "Mouse",
       "Kangaroo",
       "Goat",
       "Horse",
       "Monkey",
       "Koala",
       "Elephant",
       "Leopard",
       "Hippopotamus",
       "Giraffe",
       "Fox",
       "Coyote",
       "Hedgehog",
       "Sheep",
       "Deer"]

resoning_words = [
       'in recent years',
       'trend',
       'tend',
       'reported',
       'is famous for',
       'is known for',
       'since',
       'well-known',
       'always',
       'never',
       'sometimes',
       'actually',
       'can be found',
       'really',
       'certainly',
       'seems',
       'known',
       'ever',
       'forever',
       'definitely',
       'obviously',
       'indeed',
       'surely',
       'hardly',
       'nothing',
       'eventuality',
       'constantly',
       'night and day',
       'often',
       'uninterruptedly',
       'inevitably'
]